### ISSUE TITLE
Refreshing video duration for live content?

### ISSUE THREAD

**Issue by mtkennerly** [jazzfool/iced_video_player#22]
I'm not sure how feasible this is, but wanted to bring up the use case.

I'd like to be able to do something like this using [Streamlink](https://github.com/streamlink/streamlink):

```
streamlink https://www.twitch.tv/${channel} best -o "${channel}.ts"
```

and then watch the file while it's being written during a livestream. I just tested it, and it works fine, except that  the video duration is fixed at the point when it's loaded. The video will keep playing past that point and just report a current timestamp greater than the total time. For reference, VLC does the same thing (stuck at "1 second remaining").

Would this be feasible or appropriate for the crate to support? I'm not sure if it's a GStreamer limitation or if they have a way to refresh the total duration.

**Comment by jazzfool** [comment]
Updating the duration should already be possible, except you would need to keep track of it yourself and won't be able to use `Video::duration`.
With `streamlink`, for example, you can do something like
```rust
let pipeline = video.pipeline();
my_duration = Duration::from_nanos(
   pipeline
      .query_duration::<gst::ClockTime>()
      .map(|duration| duration.nseconds())
      .unwrap_or(0),
);
```
and you can see the duration tick up in increments as the TS chunks arrive. You'd just need to use `my_duration` instead of `Video::duration`.

This is a fairly niche use-case, and it doesn't seem GStreamer emits any messages to the bus in this case (so it wouldn't be any more efficient, nor could it publish an Iced message when it happens) - so I'm not sure whether it would be worth integrating.

**Comment by mtkennerly** [comment]
Oh, nice 👍 I should read up on the underlying pipeline methods. Thank you.

Using that approach, the duration seems to update once every 5~7 seconds, which is fine. Using `Video::seek` too close to the end can be a bit fiddly, though, triggering the end of stream event and stopping playback even if I don't seek all the way to the end. I tried using the underlying seek method directly, and it seems the same, so I imagine that's just how GStreamer behaves.
